pipelines:
  default:
    - parallel:
      - step:
          name: Validate README.md using terraform-docs
          image: quay.io/terraform-docs/terraform-docs:0.16.0 # Same version (container tag) as in .pre-commit-config.yaml
          script:
            - apk --no-cache add git
            - terraform-docs .        # Same arguments in .pre-commit-config.yaml
            - git diff --exit-code    # Check if anything modified any files
      - step:
          name: Validate README.md TOC
          image: docker.io/library/node:18-alpine
          caches:
            - node
          script:
            - apk --no-cache add git
            - npm install --global markdown-toc@1.2.0
            - markdown-toc README.md -i --indent "    " # Same arguments in .pre-commit-config.yaml
            - git diff --exit-code                      # Check i
      - step:
          name: Validate Terraform format using terraform fmt
          image: docker.io/hashicorp/terraform:latest
          script:
            - apk --no-cache add git
            - terraform fmt -no-color -write=true # Same arguments in .pre-commit-config.yaml
            - git diff --exit-code                # Check if anything modified any files
